version: '3.8'

services:
  ksm-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: keeper-mcp:latest
    container_name: ksm-mcp-server
    
    # Environment variables
    environment:
      - KSM_MCP_CONFIG_DIR=/home/keeper/.keeper/ksm-mcp
      - KSM_MCP_PROFILE=${KSM_PROFILE:-production}
      - KSM_MCP_LOG_LEVEL=${LOG_LEVEL:-info}
      - KSM_MCP_BATCH_MODE=${BATCH_MODE:-false}
      # Optional: for automated environments
      - KSM_MCP_PROTECTION_PASSWORD_SECRET_PATH=/run/secrets/dev_protection_password
    
    # Volumes for persistent data
    volumes:
      # Config directory - can be bind mounted or named volume
      - ./config:/home/keeper/.keeper/ksm-mcp:rw
      # Alternative: use named volume
      # - ksm-config:/home/keeper/.keeper/ksm-mcp
      
      # Logs directory
      - ./logs:/var/log/ksm-mcp:rw
      
      # Optional: Mount local development code for hot reload
      # - ./:/workspace:ro
    
    # Docker secrets for sensitive data
    secrets:
      - ksm_token
      - ksm_config
      - dev_protection_password
    
    # For interactive mode
    stdin_open: true
    tty: true
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # Health check
    healthcheck:
      test: ["CMD", "ksm-mcp", "test", "--profile", "docker"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Network configuration (isolated)
    networks:
      - ksm-network

  # Optional: Claude Desktop integration example
  claude-desktop:
    image: anthropic/claude-desktop:latest
    container_name: claude-desktop
    environment:
      - MCP_SERVER_URL=stdio://ksm-mcp:8080
    depends_on:
      ksm-mcp:
        condition: service_healthy
    networks:
      - ksm-network
    profiles:
      - claude

# Networks
networks:
  ksm-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Volumes (optional, if using named volumes)
volumes:
  ksm-config:
    driver: local
  ksm-logs:
    driver: local

# Secrets definitions
secrets:
  ksm_token:
    file: ./secrets/ksm_token.txt
    # Alternative: external secret created with docker secret create
    # external: true
  
  ksm_config:
    file: ./secrets/ksm_config.json
    # external: true
  
  dev_protection_password:
    file: ./secrets/dev_protection_password.txt
    # external: true

  ksm_config_dev:
    file: ./secrets/ksm_config.json