services:
  ksm-mcp:
    image: ksm-mcp:latest
    container_name: ksm-mcp-test
    environment:
      - KSM_MCP_CONFIG_DIR=/home/keeper/.keeper/ksm-mcp
      - KSM_MCP_LOG_LEVEL=debug
      - KSM_MCP_BATCH_MODE=true
      - KSM_CONFIG_BASE64=ewogICJjbGllbnRJZCI6ICJ0ZXN0LWNsaWVudC1pZCIsCiAgImFwcEtleSI6ICJ0ZXN0LWFwcC1rZXkiLAogICJwcml2YXRlS2V5IjogInRlc3QtcHJpdmF0ZS1rZXkiLAogICJob3N0bmFtZSI6ICJ0ZXN0Lmtlc2VwZXJzZWN1cml0eS5jb20iCn0=
    stdin_open: true
    tty: true
    command: serve --batch --auto-approve