# Minimal KSM MCP Docker Compose - Just add your base64 config!
version: '3'
services:
  ksm-mcp:
    image: keepersecurityinc/ksm-mcp-poc:latest
    environment:
      - KSM_CONFIG_BASE64=YOUR_BASE64_CONFIG_STRING_HERE
    volumes:
      - ~/.keeper/ksm-mcp:/home/ksm/.keeper/ksm-mcp
    stdin_open: true
    tty: true

# That's it! Run with: docker-compose up
# The container will auto-initialize on first run using the base64 config.
#
# For production setups with more options, see:
# https://github.com/Keeper-Security/ksm-mcp/blob/main/docs/DEPLOYMENT.md